# https://taskfile.dev

version: '3'

vars:
  OAI_ENDPOINT: https://www.e-manuscripta.ch/zuzcmi/oai

tasks:
  
  retrieve-data-from-e-manuscripta:
    desc: Merge the source data with records retrieved from e-manuscripta
    cmds:
      - python retrieveDataFromEManuscripta.py --endpoint {{.OAI_ENDPOINT}} --inputFolder /data/source/ --outputFolder /data/xml/oai/