# https://taskfile.dev

version: '3'

vars:
  OAI_ENDPOINT: https://www.e-manuscripta.ch/zuzcmi/oai

tasks:

  default:
    desc: Runs the entire pipeline
    cmds:
      - task: retrieve-data-from-e-manuscripta
      - task: prepare-data-for-mapping

  prepare-data-for-mapping:
    desc: Prepare the source and OAI data for mapping
    sources:
      - /scripts/prepareDataForMapping.py
      - /data/source/*.json
      - /data/xml/oai/*.xml
    generates:
      - /data/xml/merged/*.xml
    cmds:
      - python prepareDataForMapping.py --sourceFolder /data/source --oaiXMLFolder /data/xml/oai --outputFolder /data/xml/merged
  
  retrieve-data-from-e-manuscripta:
    desc: Retrieve the OAI records from from e-manuscripta
    sources:
      - /script/retrieveDataFromEManuscripta.py
      - /data/source/*.json
    generates:
      - /data/xml/oai/*.xml
    cmds:
      - python retrieveDataFromEManuscripta.py --endpoint {{.OAI_ENDPOINT}} --inputFolder /data/source/ --outputFolder /data/xml/oai/